[versions]
androidsvg = "1.4"
core = "1.7.0"
gradle = "9.0.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
kxml2 = "2.3.0"
constraintlayout = "2.2.1"
mqttv5 = "1.2.5"
jakartaMail = "2.0.2"
bouncycastle = "1.70"
okhttp = "5.3.2"
playServicesLocation = "21.3.0"
preference = "1.2.1"
webkit = "1.15.0"
zip4j = "2.11.5"

[libraries]
androidsvg = { module = "com.caverock:androidsvg", version.ref = "androidsvg" }
androidx-rules = { module = "androidx.test:rules", version.ref = "core" }
androidx-runner = { module = "androidx.test:runner", version.ref = "core" }
androidx-webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
core = { module = "androidx.test:core", version.ref = "core" }
espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espressoCore" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kxml2 = { module = "net.sf.kxml:kxml2", version.ref = "kxml2" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
mqttv5 = { group = "org.eclipse.paho", name = "org.eclipse.paho.mqttv5.client", version.ref = "mqttv5" }
jakarta-mail = { group = "com.sun.mail", name = "jakarta.mail", version.ref = "jakartaMail" }
bcprov = { group = "org.bouncycastle", name = "bcprov-jdk15on", version.ref = "bouncycastle" }
bcpkix = { group = "org.bouncycastle", name = "bcpkix-jdk15on", version.ref = "bouncycastle" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
preference = { module = "androidx.preference:preference", version.ref = "preference" }
zip4j = { module = "net.lingala.zip4j:zip4j", version.ref = "zip4j" }

[plugins]
